server:
  port: 80

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      #Nacos服务注册中心地址
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path= /user/**
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path= /product/**
