server:
  port: 8763
eureka:
  instance:
    hostname: eureka-peer3
  client:
    register-with-eureka: true  #一定要设置为true或者不写,否则会出现unavailable-replicas
    fetch-registry: true     #一定要设置为true或者不写,否则会出现unavailable-replicas
    service-url:
      defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/

