server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_permission?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

rbac:
  spring:
    security:
      browser:
        loginSuccessReturnType: JSON
      code:
        image:
          width: 50
      social:
        qq:
          app-id: 101843871
          app-secret: 0d0144e363854c3665b56df341bafcdc


